---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE}
system("mkdir -p Figures")
source('Rscripts/utils.R')
```

```{r}
ff="CAGE-validation/sr.tbl.gz"
a=fread(ff)
ff="CAGE-validation/ft.tbl.gz"
b=fread(ff)
keep=unique(a$query_name)
keep2=unique(b$query_name)
bin_size = 20
cage = bind_rows(list(fibertools=b, subread=a), .id="Tool") %>% 
    filter(centered_position_type == "m6a" ) %>%
    filter(query_name %in% keep) %>%
    filter(query_name %in% keep2) %>%
    mutate(
        group = 5000 * floor(query_length / 5000), 
        group = case_when(
            group > 30000 ~ 30000,
            TRUE ~ group
        ),
        bin = bin_size*floor(centered_start/bin_size) + bin_size/2,
    ) 

z=data.table(
    label = paste(comma(unique(cage$group)), "-", comma(unique(cage$group+ 5000)), "bp", sep=" "),
    group=unique(cage$group)
)

cage = merge(cage,z, by="group") %>%
    arrange(group) %>%
    mutate(
        label = factor(label, levels=unique(label)),
    )
#cage$label[cage$group == 30000] = factor("> 30,000 bp")
```

```{r}
p.data=cage %>% 
    group_by(label) %>%
    mutate(
        n_fibers = length(unique(query_name))
    ) %>%
    group_by(label, bin, Tool, n_fibers) %>%
    summarise(
        value = n(),
    )
p.sum = p.data %>% group_by(label, n_fibers) %>% summarise(value=max(value))
cage_plot= p.data%>%
    #filter(query_length < 30e3)  %>%
    #group_by(group) %>% filter(row_number() < 1e5) %>% 
    ggplot(
        aes(x=bin, y=value, fill=Tool)
    ) +
    geom_histogram(
        binwidth=10,
        position="identity",
        stat="identity",
        alpha=0.85,
    ) +
    geom_text(
        data = p.sum,
        aes(
            label=paste("n = ", comma(n_fibers)),
            x=-1900,
            y=value*0.90,
            fill=NULL,
        ),
        hjust=0,
        vjust=0,
        size=2.5,
        color="black"
    ) +
    scale_x_continuous("Distance from CAGE positive TSS", label=comma) +
    scale_y_continuous("# m6A calls", label=comma)+
    scale_fill_manual(
        "",
        values=c("purple", "darkgreen")
    )+
    theme_minimal_grid(font_size=10) +
    facet_wrap(
        ~label,
        scale="free_y",
        ncol=2
    ) +
    theme(
        legend.position="top"
    )
my_ggsave("Figures/CAGE.pdf", height=5, width=7)
```