```{r}
source('Rscripts/utils.R')
library("purrr")
library("reticulate")
```


```{r}
start = 119084601 
end = 119085100
mid = round((start+end)/2)
region = glue("chr11\t{mid}\t{mid+1}")
fileConn<-file("temp.bed")
writeLines(c(region), fileConn)
close(fileConn)

files = Sys.glob("results/ft_PS00109_*/ft_PS00109_?.fiberseq.bam")
files = c(files, Sys.glob("results/PS00109_*/PS00109_?.fiberseq.bam"))

files = c(
    "validation_data/PS00243-m6A-ML-val-Fiber-seq-bc2017/PS00243_ML.fiberseq.bam",
    "../fiberseq-smk/results/PS00243_subread/PS00243_subread.fiberseq.bam"
)

files = Sys.glob("../fiberseq-smk/results/ft_PS00075*/ft_PS00075*.fiberseq.bam")
files = c(files, Sys.glob("results/PS00075_*/PS00075_?.fiberseq.bam"))

files

dfs = list()
dfs2 = list()
for (file in files) {
    cmd = glue('ft center -r -d 500 {file} temp.bed')
    dfs[[file]]=fread(cmd=cmd)
    cmd = glue("samtools view -u -M -L temp.bed {file} | ft extract -s --all -")
    dfs2[[file]]=fread(cmd=cmd)
}
```


```{r}
fiber_tbl = bind_rows(dfs2) %>%
    group_by(fiber, ec) %>%
    summarise(
        query_name = unique(fiber)
    )

combo = bind_rows(dfs, .id="tool") %>% 
    filter(centered_position_type=="m6a") %>%
    mutate(
        is_ft = grepl("ft_", tool) | grepl("_ML", tool),
        centered_start = centered_start + mid,
    ) %>%
    group_by(query_name, centered_start, reference_start, reference_end ) %>%
    summarise(
        case = case_when(
            n() == 2 ~ "both",
            n() > 2 ~ "weird",
            is_ft ~ "fibertools",
            TRUE ~ "subread"
        )
    ) %>%
    ungroup() %>%
    group_by(query_name, reference_start, reference_end) %>%
    filter(centered_start >= start & centered_start <= end) %>%
    filter(reference_start <= start & reference_end >= end) %>%
    filter(n()> 10) %>%
    merge(fiber_tbl, by="query_name") %>%
    mutate(frac_new = sum(case=="fibertools")/n()) %>%
    ungroup() %>%
    arrange(-ec) %>%
    mutate(
        case=factor(case),
        query_name=factor(query_name, levels=unique(query_name)),
        y = as.numeric(query_name)
    ) %>%
    data.table()
combo
```


```{r}
combo %>%
    ggplot(
        aes(x=centered_start, color=NULL, fill=case)
    )+
    #geom_point(alpha=0.5)+
    #geom_hline(aes(yintercept=y), size = 0.1) +
    geom_rect(
        aes(ymin=y-0.45, ymax=y+0.45, xmin=centered_start, xmax=centered_start+0.9),
        size=-0
    ) +
    geom_xsidedensity(aes(x=centered_start), adjust=0.15, fill="darkgray") +
    #scale_xsidey_continuous(name="m6A density") +
    geom_ysidehistogram(
        aes(y=y), 
        position="fill",
        binwidth=1
    ) +
    scale_ysidex_continuous(
        breaks=c(0.0, 0.5, 1.00),
        #guide = guide_axis(angle = -90),
        position="top",
    ) +
    scale_y_continuous(
        "Fiber-seq reads",
        breaks = seq(max(combo$y)),
        labels = rep("", max(combo$y)),
    ) +
    scale_x_continuous("Genomic position", label=comma) +
    #scale_color_manual(
    #    values = c(subread="green", both="darkgray", fibertools="purple")
    #) +
    scale_fill_manual("",
        values = c(subread=Teal, both="gray", fibertools="purple"),
        labels = c("Subread pipeline", "Both", "fibertools"),
    ) +
    #facet_col(~is_ft) +
    theme_minimal_hgrid() +
    theme(
        legend.position="top"
    )

s=1.2
my_ggsave("Figures/HMBS_reference.pdf", width=9, height=5)
```

#
# Plasmid
#
```{r}
dam_positions = c(
    230,
372,
462,
634,
774,
1073,
1825,
2023,
2083,
2168,
2902,
2938,
2955,
3213,
3259,
3277,
3618,
3723,
3735,
3813,
3821,
3832,
3907)
dam_positions = sort(c(dam_positions+1, dam_positions+2))
hsd_positions = c(
    2916, #seq(2808, 2820),
    2925 #seq(2915, 2927)
)

start = 1000 
end = 1000
mid = round((start+end)/2)
region = glue("linear_LeaGFP\t{mid}\t{mid+1}")
fileConn<-file("temp.bed")
writeLines(c(region), fileConn)
close(fileConn)

files = c("validation_data/from_ben/aln.m6a.1.bam", "validation_data/from_ben/aln.m6a.2.bam")
files

dfs = list()
dfs2 = list()
for (file in files) {
    cmd = glue('ft center -r {file} temp.bed')
    dfs[[file]]=fread(cmd=cmd)
    cmd = glue("samtools view -u -M -L temp.bed {file} | ft extract -s --all -")
    dfs2[[file]]=fread(cmd=cmd)
}

fiber_tbl = bind_rows(dfs2) %>%
    group_by(fiber, ec, total_AT_bp, total_m6a_bp) %>%
    summarise(
        query_name = unique(fiber)
    )
```

```{r}
combo = bind_rows(dfs, .id="tool") %>% 
    filter(centered_position_type=="m6a") %>%
    group_by(query_name) %>%
    mutate(
        centered_start=centered_start+1000,
        count = n()
    ) %>%
    ungroup() %>%
    arrange(-count) %>%
    mutate(
        case=case_when(
            centered_start %in% dam_positions ~ "Dam",
            centered_start %in% hsd_positions ~ "hsdM",
            TRUE ~ "Other",
        ),
        z = factor(query_name, levels = unique(query_name)),
        y = as.numeric(z)
    )
print(max(combo$y))
```


```{r}
tdf = combo %>%
    filter( y > 19500) 
tdf %>%
    ggplot(
        aes(x=centered_start, color=NULL, fill=case)
    )+
    #geom_point(alpha=0.5)+
    #geom_hline(aes(yintercept=y), size = 0.1) +
    geom_rect(
        aes(ymin=y-0.45, ymax=y+0.45, xmin=centered_start, xmax=centered_start+0.9),
        size=-0
    ) +
    geom_xsidehistogram(aes(x=centered_start), binwidth=1) +
    #scale_xsidey_continuous(name="m6A density") +
    scale_y_continuous(
        "Fiber-seq reads",
        breaks = seq(max(tdf$y)),
        labels = rep("", max(tdf$y)),
    ) +
    scale_x_continuous("Genomic position", label=comma) +
    scale_fill_manual("",
        values = c("Other"=Teal, "Dam"="purple"),
    ) +
    #facet_col(~is_ft) +
    theme_minimal_hgrid() +
    theme(
        legend.position="top"
    )


s=1.2
my_ggsave("Figures/Plasmid_reference.pdf", width=9, height=5)
```

```{r}
tdf = combo %>% 
    group_by(tool) %>%
    mutate(
        k = length(unique(query_name)),
        tool = case_when(
            tool == "validation_data/from_ben/aln.m6a.1.bam" ~ "Dam and hsdM negative",
            TRUE ~ " Dam and hsdM positive"
        ),
        width = case_when(
            case == "Dam" ~ 6,
            TRUE ~ 1    
        )
    ) %>%
    group_by( centered_start,case, tool, k) %>%
    summarise(
        count = 100*n()/unique(k)
    ) %>%
    data.table()
tdf %>% 
    group_by(tool, case) %>%
    summarise(
        percent_m6a=mean(count)
    )
tdf %>%
    ggplot(
        aes(
            x=centered_start,
            y=count,
            fill=case,
            color=case,
        ),
    ) +
    geom_hline(
        data = . %>% group_by(case, tool) %>% summarise(count = mean(count)), 
        aes(yintercept=count, color=case),
        linetype="dashed"
    )+
    geom_text_repel(
        data = . %>% group_by(case, tool) %>% summarise(count = mean(count)), 
        aes(y=count, x = 0, label=paste0(round(count,1), "%")),
        direction="y",
        min.segemnt.length = 0,
        force = 8,
        nudge_y=1,
        size = 3,
    )+
    geom_point(data = . %>% filter(case != "Other"), shape=21, size = 1, color="black") + 
    geom_bar(,
        color=NA,
        stat="identity",
        width = 4, #. %>% select(width) %>% as.list(),
    ) +
    geom_text_repel(
        data = . %>% filter(case=="Dam" & tool==" Dam and hsdM positive") %>% filter(FALSE),
        aes(label=round(count,1)),
        size=2.5,
        min.segment.length=0,
        max.overlaps=100,
        segment.alpha=0.75,
        segment.size = 0.1,
        arrow = arrow(length = unit(0.015, "npc"))
        #nudge_x=50, 
        #direction="x",
        #vjust=0.1,
    ) +
    scale_y_continuous(
        "Percent m6A",
        #limits = c(0,110),
        breaks = seq(0,100,25),
    )+
    facet_col(~tool) +
    scale_x_continuous("Plasmid position", label=comma) +
    scale_fill_manual("",
        values = c(Other=Teal, Dam="purple", hsdM="orange"),
    ) +
    scale_color_manual("",
        values = c(Other=Teal, Dam="purple", hsdM="orange"),
    ) +
    theme_minimal_hgrid() +
    theme(
        legend.position="none",
        #axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
    )
my_ggsave("Figures/Plasmid_simple_reference.pdf", width=9, height=5)

```
