---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE}
system("mkdir -p Figures")
source('Rscripts/utils.R')
```

```{r}
fdr.df = fread(
    cmd= "zcat ../GM12878_aCRE_2022-08-16/results/Phased_GM12878_all/acc.model.results.bed.gz | grep -v '230,230,230' | grep -v '147,112,219' | head -n 10000000"
)
fdr.df
```


```{r}
fdr.df = fread(
    cmd= "bgzip -@ 8 -cd ../GM12878_aCRE_2022-08-16/results/chr20_GM12878_all/acc.model.results.bed.gz | grep -v '230,230,230' |  head -n 100000000"
)
# grep -v '147,112,219' |
fdr.df
```

```{r}
fdr.df = fread(
    cmd= "bgzip -@ 8 -cd  ../GM12878_aCRE_2022-08-16/results/old_*new_feats/acc.model.results.bed.gz | grep -v '230,230,230' | head -n 100000000"
)
#grep -v '147,112,219' 
fdr.df
```

```{r}
fdr.df$l = fdr.df$en -fdr.df$st 
fdr.df[l>500]$l = 500
fdr.df %>%
    filter(l > 1) %>%
    #filter(qValue < 0.15) %>%
    group_by(color) %>%
    mutate(
        idx = seq(n()),
        max_fdr = factor(round(max(qValue),2)), 
    ) %>%
    filter(idx < 1e6) %>%
    mutate(
        label = paste0(max_fdr, "   n=", comma(n())),
    ) %>%
    ggplot(aes(x=l, fill=max_fdr)) +
    geom_histogram(binwidth=5) +
    geom_vline(aes(xintercept=85), linetype="dashed") +
    facet_col(~label, scales="free_y") +
    theme_minimal_grid()
my_ggsave("../phased-fdr-and-peaks/figures/msp_sizes_by_fdr.pdf", width = 8, height=8)
```